"""
Find out why the seating plan is missing from a ticket PDF.

Whatever the cause -- cairo not loadable, the plan rejected, the image element
missing from the ticket layout, no seat recorded for the order, a stale cached
PDF -- the symptom on the ticket is the same: a grey box, or nothing. pretix's
renderer swallows the error, so this command walks the whole chain on the
server and prints which link is broken.

    python -m pretix simpleseating_ticket_check organizer/event --order ABC12

Run it with the same Python environment as the pretix web and Celery workers:
tickets are generated by the workers, so cairo has to be usable there.
"""
import json
import logging
import sys
from io import BytesIO

from django.core.management.base import BaseCommand, CommandError
from django_scopes import scopes_disabled

from pretix.base.i18n import language
from pretix.base.models import CachedCombinedTicket, CachedTicket, Event, Order

from ...models import SeatingConfig
from ...svg_sanitize import SvgSanitizeError, sanitize_svg
from ...ticket_image import render_seat_plan_png, resolve_seat_for_position

PDF_PLUGIN = 'pretix.plugins.ticketoutputpdf'
IMAGE_VARIABLE = 'simpleseating_plan'


class _Collector(logging.Handler):
    """Keeps what the plugin logs while rendering, so the real error can be shown."""

    def __init__(self):
        super().__init__(level=logging.WARNING)
        self.messages = []

    def emit(self, record):
        text = record.getMessage()
        if record.exc_info and record.exc_info[1] is not None:
            text += ' -- %s: %s' % (type(record.exc_info[1]).__name__, record.exc_info[1])
        self.messages.append(text)


class Command(BaseCommand):
    help = 'Diagnose why the seating plan does not appear on a ticket PDF (checks cairo, the plan, the layout, the order\'s seat, a real PDF).'

    def add_arguments(self, parser):
        parser.add_argument('event', help='organizer/event-slug')
        parser.add_argument('--order', help='order code of a ticket that shows the problem (recommended)')
        parser.add_argument('--position', type=int, help='position number within the order (default: the first seat ticket)')
        parser.add_argument('--png', help='save the rendered plan image to this file')
        parser.add_argument('--clear-cache', action='store_true',
                            help="delete this order's cached ticket files so they are regenerated on the next download")

    # -- output helpers ---------------------------------------------------------
    def _line(self, tag, label, detail=''):
        self.stdout.write('[%s] %s%s' % (tag, label, (': ' + detail) if detail else ''))

    def ok(self, label, detail=''):
        self._line(' OK ', label, detail)

    def warn(self, label, detail=''):
        self._line('WARN', label, detail)

    def info(self, label, detail=''):
        self._line('INFO', label, detail)

    def fail(self, label, detail=''):
        self.failures += 1
        self._line('FAIL', label, detail)

    # -- main -------------------------------------------------------------------
    # pretix models are organizer-scoped and a command has no request to activate a scope.
    @scopes_disabled()
    def handle(self, *args, **options):
        self.failures = 0
        try:
            organizer_slug, event_slug = options['event'].split('/', 1)
        except ValueError:
            raise CommandError('The event must be given as organizer/event-slug.')
        try:
            event = Event.objects.select_related('organizer').get(organizer__slug=organizer_slug, slug=event_slug)
        except Event.DoesNotExist:
            raise CommandError('No event %s.' % options['event'])

        order = None
        if options['order']:
            order = Order.objects.filter(event=event, code=options['order'].strip().upper()).select_related('sales_channel').first()
            if not order:
                raise CommandError('No order %s in %s.' % (options['order'], options['event']))

        self.info('python', '%s (pretix %s)' % (sys.executable, self._pretix_version()))
        self.info('where this must work',
                  'ticket PDFs are generated by the Celery workers. This command only proves something about the '
                  'environment it runs in: run it with the same Python/virtualenv/container as the workers, and '
                  'restart the workers after installing cairosvg or libcairo.')

        try:
            cfg = SeatingConfig.objects.get(event=event)
        except SeatingConfig.DoesNotExist:
            self.fail('configuration', 'this event has no seating plan configuration')
            raise CommandError('1 problem found.')
        if not cfg.item_id:
            self.fail('configuration', 'no ticket item is configured for the seating plan')
        if 'pretix_simpleseatingplan' not in event.get_plugins():
            self.fail('plugin', 'the seating plan plugin is not enabled for this event')

        svg_ok = self._check_plan(cfg)
        self._check_cairo()
        pdf_plugin_on = self._check_layout(event, cfg, order)

        if order is None:
            self.info('order', 'no --order given: only the server-side checks ran. Re-run with --order CODE to check a real ticket.')
        else:
            self._check_order(event, cfg, order, options, svg_ok, pdf_plugin_on)

        if self.failures:
            raise CommandError('%d problem(s) found, see the [FAIL] lines above.' % self.failures)
        self.stdout.write('No problem found.')

    # -- individual checks ------------------------------------------------------
    def _pretix_version(self):
        try:
            import pretix
            return pretix.__version__
        except Exception:
            return '?'

    def _check_plan(self, cfg):
        if not cfg.svg:
            self.fail('stored plan', 'no plan has been uploaded for this event')
            return False
        try:
            cleaned = sanitize_svg(cfg.svg)
        except SvgSanitizeError as e:
            self.fail('stored plan', 'the plan is rejected by the sanitizer and is therefore shown nowhere (checkout and ticket): %s' % e)
            return False
        seats = cleaned.count(' id="%s' % cfg.seat_id_prefix)
        if not seats:
            self.fail('stored plan', 'the plan has no element whose id starts with the configured prefix "%s", so no seat '
                                     'can ever be found in it (wrong "seat id prefix" in the settings, or a plan without seat ids)'
                      % cfg.seat_id_prefix)
            return False
        self.ok('stored plan', '%d bytes stored, %d after sanitizing, %d seat element(s) with the prefix "%s"'
                % (len(cfg.svg), len(cleaned), seats, cfg.seat_id_prefix))
        return True

    def _check_cairo(self):
        hint = ('The Python package cairosvg needs the system library libcairo (Debian/Ubuntu: apt install libcairo2; '
                'Alpine: apk add cairo). It must be present in the environment that runs the Celery workers, and the '
                'workers must be restarted after installing it.')
        try:
            import cairosvg
            import cairocffi
        except ImportError as e:
            self.fail('cairo', 'cairosvg is not installed in this Python environment (%s). Install it with pip in the '
                               'same virtualenv as pretix.' % e)
            return
        except OSError as e:
            self.fail('cairo', 'cairosvg could not load libcairo: %s. %s' % (e, hint))
            return
        try:
            lib_version = cairocffi.cairo_version_string()
        except OSError as e:
            self.fail('cairo', 'libcairo could not be loaded: %s. %s' % (e, hint))
            return
        try:
            png = cairosvg.svg2png(
                bytestring=b'<svg xmlns="http://www.w3.org/2000/svg" width="10" height="10"><rect width="10" height="10"/></svg>')
        except Exception as e:
            self.fail('cairo', 'cairosvg %s / libcairo %s are present but a test drawing failed: %s: %s'
                      % (getattr(cairosvg, '__version__', '?'), lib_version, type(e).__name__, e))
            return
        self.ok('cairo', 'cairosvg %s, libcairo %s, test drawing produced %d bytes'
                % (getattr(cairosvg, '__version__', '?'), lib_version, len(png)))

    @staticmethod
    def _has_plan_element(layout):
        try:
            elements = json.loads(layout.layout) or []
        except (ValueError, TypeError):
            return False
        return any(isinstance(o, dict) and o.get('type') == 'imagearea' and o.get('content') == IMAGE_VARIABLE
                   for o in elements)

    def _check_layout(self, event, cfg, order):
        """Returns True if the PDF ticket plugin is enabled."""
        if PDF_PLUGIN not in event.get_plugins():
            self.fail('ticket layout', 'the PDF ticket output plugin (%s) is not enabled for this event, so there is '
                                       'no PDF ticket to put the plan on' % PDF_PLUGIN)
            return False
        from pretix.plugins.ticketoutputpdf.models import TicketLayoutItem

        channel = order.sales_channel.identifier if order else 'web'
        assigned = {
            a.sales_channel.identifier: a.layout
            for a in TicketLayoutItem.objects.filter(item_id=cfg.item_id).select_related('layout', 'sales_channel')
        }
        layouts = list(event.ticket_layouts.all())
        used = assigned.get(channel) or assigned.get('web') or next((l for l in layouts if l.default), None)
        if used is None:
            self.fail('ticket layout', 'no ticket layout is assigned to the seat ticket item and there is no default '
                                       'layout: pretix uses its built-in layout, which has no seating plan')
        elif self._has_plan_element(used):
            self.ok('ticket layout', 'the layout used by this ticket ("%s") contains the seating plan element' % used.name)
        else:
            detail = ('the layout used by this ticket ("%s") has no image element with the content "%s". In the ticket '
                      'designer add an "Image area" and choose "Seating plan with purchased seat highlighted".' % (used.name, IMAGE_VARIABLE))
            others = [l.name for l in layouts if l.pk != used.pk and self._has_plan_element(l)]
            if others:
                detail += ' The layout(s) %s contain it, but that is not the layout used by this ticket.' % ', '.join('"%s"' % n for n in others)
            self.fail('ticket layout', detail)
        return True

    def _check_order(self, event, cfg, order, options, svg_ok, pdf_plugin_on):
        if order.status != Order.STATUS_PAID:
            self.warn('order status', '%s: pretix issues no ticket for an unpaid order (unless tickets before payment are enabled)' % order.status)

        positions = [p for p in order.positions.all() if p.item_id == cfg.item_id]
        if options['position']:
            positions = [p for p in positions if p.positionid == options['position']]
        if not positions:
            self.fail('seat of the order', 'no ticket of the seat item (id %s) found in this order%s'
                      % (cfg.item_id, ' at that position' if options['position'] else ''))
            return
        pos = positions[0]

        seat_guid, seat_label = resolve_seat_for_position(event, cfg, pos)
        if not seat_guid:
            self.fail('seat of the order', 'position %d has no recorded seat and its "Seat" answer matches no seat, so '
                      'no plan can be drawn. Run "simpleseating_audit" to list and repair such orders.' % pos.positionid)
        else:
            self.ok('seat of the order', '%s (seat id %s, position %d)' % (seat_label or '?', seat_guid, pos.positionid))
            if svg_ok:
                self._check_render(event, cfg, seat_guid, seat_label, options['png'])

        if pdf_plugin_on:
            self._check_pdf(event, order, pos)
        self._check_cache(order, pos, options['clear_cache'])

    def _check_render(self, event, cfg, seat_guid, seat_label, png_path):
        collector = _Collector()
        logger = logging.getLogger('pretix_simpleseatingplan.ticket_image')
        logger.addHandler(collector)
        try:
            png = render_seat_plan_png(event, cfg, seat_guid, seat_label)
        finally:
            logger.removeHandler(collector)
        if not png:
            self.fail('plan image', 'the plan could not be drawn for this seat. %s'
                      % (' | '.join(collector.messages) or 'No details were logged.'))
            return
        self.ok('plan image', 'drawn as a %d-byte PNG with the seat highlighted' % len(png))
        if png_path:
            with open(png_path, 'wb') as f:
                f.write(png)
            self.info('plan image', 'saved to %s' % png_path)

    def _check_pdf(self, event, order, pos):
        from pypdf import PdfReader
        from pretix.plugins.ticketoutputpdf.ticketoutput import PdfTicketOutput
        try:
            with language(order.locale, event.settings.region):
                _name, _mime, data = PdfTicketOutput(event).generate(pos)
        except Exception as e:
            self.fail('ticket PDF', 'generating the ticket failed: %s: %s' % (type(e).__name__, e))
            return
        try:
            images = sum(len(page.images) for page in PdfReader(BytesIO(data)).pages)
        except Exception as e:
            self.warn('ticket PDF', 'generated (%d bytes) but could not be inspected: %s' % (len(data), e))
            return
        if images:
            self.ok('ticket PDF', 'generated (%d bytes) and it contains %d image(s): the plan is printed' % (len(data), images))
        else:
            self.fail('ticket PDF', 'generated (%d bytes) but contains no image: the plan is missing (pretix draws a grey '
                                    'box, or nothing, when the image element is absent or its image could not be produced)' % len(data))

    def _check_cache(self, order, pos, clear):
        tickets = list(CachedTicket.objects.filter(order_position=pos))
        combined = list(CachedCombinedTicket.objects.filter(order=order))
        total = len(tickets) + len(combined)
        if clear:
            for ct in tickets + combined:
                ct.delete()
            self.ok('cached ticket', 'deleted %d cached ticket file(s); they are regenerated on the next download' % total)
        elif total:
            dates = ', '.join(sorted({ct.created.strftime('%Y-%m-%d %H:%M') for ct in tickets + combined}))
            self.warn('cached ticket', '%d cached ticket file(s) from %s. pretix keeps them until the order, item or layout '
                      'changes; a file generated before the seat was recorded or the plan was uploaded shows no plan. '
                      'Re-run with --clear-cache to delete them.' % (total, dates))
        else:
            self.info('cached ticket', 'none: the next download generates a fresh ticket')
