"""
Celery task used by `simpleseating_ticket_check --worker`.

Ticket PDFs are generated by the Celery workers, which can run in another
Python environment or container than the shell an administrator debugs from.
This task runs the cairo and plan-drawing checks *inside a worker* and returns
what it found. A worker that was started before this plugin version was
installed does not know the task at all, which is itself informative.
"""
import socket
import sys

from django_scopes import scopes_disabled
from pretix.celery_app import app

from .diagnostics import check_cairo, render_for_seat


def worker_check_impl(position_pk=None):
    import pretix

    result = {
        'python': sys.executable, 'host': socket.gethostname(),
        'pretix': getattr(pretix, '__version__', '?'), 'cairo': list(check_cairo()), 'render': None,
    }
    if position_pk:
        from pretix.base.models import OrderPosition
        from .models import SeatingConfig
        from .ticket_image import resolve_seat_for_position
        with scopes_disabled():
            pos = OrderPosition.all.select_related('order__event').get(pk=position_pk)
            event = pos.order.event
            cfg = SeatingConfig.objects.get(event=event)
            seat_guid, seat_label = resolve_seat_for_position(event, cfg, pos)
            if not seat_guid:
                result['render'] = [False, 'no seat could be resolved for this ticket']
            else:
                png, messages = render_for_seat(event, cfg, seat_guid, seat_label)
                if png:
                    result['render'] = [True, 'drew the plan for seat %s: %d bytes' % (seat_label, len(png))]
                else:
                    result['render'] = [False, 'could not draw the plan for seat %s. %s' % (
                        seat_label, ' | '.join(messages) or 'No details were logged.')]
    return result


@app.task
def worker_check(position_pk=None):
    return worker_check_impl(position_pk)
